#!/usr/bin/env python
import sys
import os
import optparse

from lipolib.hdlist import HdlistParser
from lipolib.rpmver import vercmp

DESCRIPTION = """\
%prog tries lists packages that are obsolete in a given repository

("obsolete" means that there are newer versions in the same repository.)
"""
USAGE = "%prog [options] <media-dir> ..."
SYNTHESIS_PATH = "media_info/synthesis.hdlist.cz"

def get_packages(synpath):
    parser = HdlistParser(synpath)
    packages = {}
    while True:
        pkg = parser.next()
        if pkg is None:
            break
        packages.setdefault(pkg.name, []).append(pkg)
    return packages

def inspect_media(mediadir, synthesis=None):
    synpath = os.path.join(mediadir, synthesis)
    packages = get_packages(synpath)
    mustfix = []
    for name, related in packages.iteritems():
        if len(related) > 1:
            versions = [(pkg.fullversion, pkg) for pkg in related]
            versions.sort(cmp=vercmp, reverse=True, key=lambda x: x[0])
            olderpkgs = [pkg for fv, pkg in versions[1:]]
            mustfix.extend(olderpkgs)
    for pkg in mustfix:
        path = os.path.join(mediadir, pkg.fullname + ".rpm")
        print path

def parse_options(args):
    parser = optparse.OptionParser(usage=USAGE, description=DESCRIPTION)
    parser.add_option("-s", "--synthesis", type="string",
        default=SYNTHESIS_PATH,
        help="path to the synthesis file for the media "\
             "(can be relative)")
    if not args:
        parser.print_help()
    return parser.parse_args(args)

def main(args):
    opts, paths = parse_options(args)
    for path in paths:
        inspect_media(path, synthesis=opts.synthesis)

if __name__ == "__main__":
    main(sys.argv[1:])

# vim:ts=4:sw=4:et
